name: Run Unit Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Install Requirements
          pip install -r requirements.txt
          # Run pytest
          pytest tests/* -vv
